name: mvvm_getx_pattern
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.7.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  path_drawing: ^1.0.1
  shimmer: ^3.0.0
  video_player: ^2.8.6
  material_design_icons_flutter: ^7.0.7296
  rive: ^0.13.8

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/lang/

